[workspace]
resolver = "2"

members = [
    "godot-bindings",
    "godot-codegen",
    "godot-ffi",
    "godot-core",
    "godot-macros",
    "godot-cell",
    "godot",
    "dodge-the-creeps/rust",

    # Godot integration
    "itest/rust",

    # utils
    "godot-fmt",
]
